# basics
model = "toy"
dataset = "toy-tiny"

[passes.quantize]
by = "type"
report = true

[passes.quantize.default.config]
name = "ternary"
data_in_scaling_factor = false
data_in_width = 2
data_in_frac_width = 0
weight_scaling_factor = false
weight_width = 2
weight_frac_width = 0
bias_scaling_factor = false
bias_width = 2
bias_frac_width = 0
