#model = "toy"
#dataset = "toy-tiny"

[passes.quantize]
by = "type"
report = true

[passes.quantize.default.config]
name = "NA"

[passes.quantize.linear.config]
name = "integer"
data_in_width = 2
data_in_frac_width = 1
weight_width = 2
weight_frac_width = 1
bias_width = 2
bias_frac_width = 1