weight_node_patterns = []
weight_nodes = [
    "model.decoder.layers.0.self_attn.q_proj",
    "model.decoder.layers.7.fc1",
]

[weight_stats.variance]
offload_to_cpu = true

[weight_stats.soft_range]
num_sigmas = 2
offload_to_cpu = true

[weight_stats.hard_range]
offload_to_cpu = true

# [weight_stats.reduced_variance]

# [weight_stats.reduced_soft_range]
# num_sigmas = 2

# [weight_stats.reduced_hard_range]
