[strategy]
name = 'analytical'

[strategy_config]
output_file = 'analytical_results.toml'

[search_space]
bias_frac_width = [0, 1, 2, 3, 4, 5, 6, 7]
bias_width = [8]
data_in_frac_width = [0, 1, 2, 3, 4, 5, 6, 7]
data_in_width = [8]
name = ['integer']
weight_frac_width = [0, 1, 2, 3, 4, 5, 6, 7]
weight_width = [8]

[search_data]
dataloader = 'train_dataloader'
num_batches = 8