# basics
model = "jsc-tiny"
dataset = "jsc"
task = "cls"

max_epochs = 5
batch_size = 256 
learning_rate = 1e-4
accelerator = "cpu"
project = "vgg_cifar10_prune"
seed = 42
log_every_n_steps = 50 

[passes.prune.weight]
sparsity = 0.2
scope = "local"
granularity = "elementwise"
method = "l1-norm"

[passes.prune.activation]
sparsity = 0.1
scope = "local"
granularity = "elementwise"
method = "l1-norm"



