from .add_common_metadata import add_common_metadata_analysis_pass
from .add_hardware_metadata import add_hardware_metadata_analysis_pass
from .add_software_metadata import add_software_metadata_analysis_pass
from .count_flop_bitops import add_flops_bitops_analysis_pass