name: Build Doc for the MASE website 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
            - info
            - warning
            - debug
  

jobs:

  software-regression-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: "true"

    # -----------
    # Mase regression test 
    # -----------
    
    - name: Get dependences 
      run: |
          sudo apt-get update
          sudo apt-get install apt-utils -y
          sudo apt-get install -y \
                          clang cmake graphviz-dev libclang-dev \
                          pkg-config g++ libxtst6 xdg-utils \
                          libboost-all-dev llvm gcc ninja-build \
                          python3 python3-pip build-essential \
                          libssl-dev git vim wget htop sudo \
                          lld python3-sphinx

          pip3 install --user --upgrade pip
          pip3 install onnx toml GitPython colorlog \
                       pytest pytorch-lightning transformers toml \
                       timm pytorch-nlp datasets IPython ipdb \
                       sentencepiece einops deepspeed pybind11 \
                       tabulate tensorboard hyperopt accelerate \
                       optuna stable-baselines3 scikit-learn
          pip3 install cocotb[bus]==1.8.0 nni
          pip3 install h5py
          pip3 install wandb==0.15.10 graphviz==0.20.1 onnxsim==0.4.33 \
                       onnxruntime==1.15.1 onnxoptimizer==0.3.13 pydot==1.4.2 \
                       protobuf==3.20.3 fpbinary==1.5.5
          pip3 install xgboost==1.7.2 --extra-index-url https://download.pytorch.org/whl/cpu
          pip3 install sphinx-rtd-theme ghp-import
    
    - name: Build sphinx html
      run: |
        cd machop/sphinx_docs
        make html

    - name: Run ghp-import
      run: |
        ghp-import -n -p -f machop/sphinx_docs/build/html

