name: Torch-MLIR Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
        - info
        - warning
        - debug

jobs:

  torch-mlir-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: "true"
    - uses: actions/setup-python@v4
      with:
          python-version: '3.11' 
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Get dependencies 
      run: |
          sudo apt-get update
          sudo apt-get install apt-utils -y
          sudo apt-get install -y \
                          clang cmake graphviz-dev libclang-dev \
                          pkg-config g++ libxtst6 xdg-utils \
                          libboost-all-dev llvm gcc ninja-build \
                          build-essential libssl-dev git vim wget htop sudo lld 
          sudo apt-get update -y
          sudo apt-get install -y \
                          perl make autoconf flex bison libunwind-dev \
                          ccache libgoogle-perftools-dev numactl \
                          perl-doc libfl2 libfl-dev zlib1g zlib1g-dev \
                          help2man libidn11-dev
    - name: Install Torch-MLIR 
      run: |
          pip install --user --upgrade pip
          pip3 install --upgrade pip 
          pip3 install --pre torch-mlir torchvision \
              -f https://llvm.github.io/torch-mlir/package-index/ \
              --extra-index-url https://download.pytorch.org/whl/nightly/cpu

    - name: Torch-MLIR regression test 
      run: |
          python3 scripts/test-torch-mlir.py

