name: Torch-MLIR Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  torch-mlir-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: "true"
    - uses: actions/setup-python@v4
      with:
          python-version: '3.10' 
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Get dependencies 
      run: |
          sudo apt-get update
          sudo apt-get install apt-utils -y
          sudo apt-get install -y \
                          clang cmake graphviz-dev libclang-dev \
                          pkg-config g++ libxtst6 xdg-utils \
                          libboost-all-dev llvm gcc ninja-build \
                          build-essential libssl-dev git vim wget htop sudo lld 
          sudo apt-get update -y
          sudo apt-get install -y \
                          perl make autoconf flex bison libunwind-dev \
                          ccache libgoogle-perftools-dev numactl \
                          perl-doc libfl2 libfl-dev zlib1g zlib1g-dev \
                          help2man libidn11-dev

    - name: Install Torch-MLIR 
      run: |
          pip install --user --upgrade pip
          pip install --pre torchvision --extra-index-url https://download.pytorch.org/whl/nightly/cpu
          pip install onnx toml GitPython  \
                              pytorch-lightning transformers toml \
                              timm pytorch-nlp datasets ipython ipdb \
                              sentencepiece einops pybind11
          wget https://github.com/llvm/torch-mlir/releases/download/snapshot-20230525.849/torch-2.1.0.dev20230523+cpu-cp310-cp310-linux_x86_64.whl
          wget https://github.com/llvm/torch-mlir/releases/download/snapshot-20230525.849/torch_mlir-20230525.849-cp310-cp310-linux_x86_64.whl
          pip install torch-*.whl torch_mlir-*.whl

    - name: Torch-MLIR regression test 
      run: |
          python scripts/test-torch-mlir.py

