# Example config file to use as a starting point.
# Please visit https://docs.beetleboxci.com/docs/config/configuration-yaml for guidance on setting up your configuration file.

# Define a runner that will be used to run a job
runners:
 ubuntu-runner:
  image: public.ecr.aws/y2s4f3y9/ubuntu-generic

# Define a job to be performed during a workflow
jobs:   
 chop-dependencies:
  # Specify the runner used to perform this job
  runner: ubuntu-runner

  # Define one or more steps to execute commands as part of the job
  steps:
   - run:
      name: Install black and clang
      command: |
        apt-get install -y \
          python3 python3-pip clang-format clang-tidy
        pip3 install --user --upgrade pip
        pip3 install black

# Define a workflow to orchestrate a job
workflows:
 mase-chop-regression:
  jobs:
   - chop-dependencies